name: Deploy to Minikube using GitHub Actions

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push request 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "job1"
  job1:
    # The type of runner that the job will run on
    name: build Node.js Docker image and deploy to minikube
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the uses
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      # Runs a set of commands using the runners shell
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
            export SHELL=/bin/bash
            eval $(minikube -p minikube docker-env)
            docker build -f ./Dockerfile -t devopshint/node-app:latest .
            echo -n "verifying images:"
            docker images
      - name: Deploy to minikube
        run:
          kubectl apply -f k8s-node-app.yaml
      - name: Test service URLs
        run: |
            minikube service list
            minikube service nodejs-app --url
